---
title: 儒一
timezone: Asia/Shanghai
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  wiki:
    title: Wiki
    output: true
    permalink: "/wiki/:path/"
baseurl: 
url: https://ruyi.ru
date_format: ordinal
subtitle: 生于行，儒于行
description: 儒一博客，生于行，儒于行
keywords: 儒一，如一，如意
encoding: utf-8
side_bar_repo_limit: 1
author: 风乐
organization: 
organization_url: 
github_username: 
location: Guangzhou, China
email: info@whooc.om
navs:
- href: "/"
  label: 首页
- href: "/categories/"
  label: 文章分类
- href: "/wiki/"
  label: 百科
- href: "/links/"
  label: 友情链接
- href: "/about/"
  label: 关于儒一
subscribe_rss: "/feed.xml"
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: "/:year/:month/:day/:title/"
gems:
- jekyll-github-metadata
- rouge
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jemoji
repository: whooc/whooc.github.io
comments_provider: disqus
gitment:
  owner: whooc
  repo: blog_comment
  oauth:
    client_id: '083ec94b416ce61952f8'
    client_secret: 2cfb5f73aae91e4faab9737c7d363063a1befef9
lazy_load_disqus: true
simple_jekyll_search:
  fulltext: false
  limit: 10
google:
  analytics_id: UA-80669434-1
  adsense:
    footer: true
    sidebar: true
    content_header: true
    content_footer: false
