# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://ruyi.ru
date_format: "ordinal"
title: 儒一
subtitle: "生于行，儒于行"
description: "儒一博客，生于行，儒于行"
keywords: 儒一，如一，如意
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 风乐
organization: 
organization_url: 
github_username: whooc
location: Guangzhou, China
email: info@whooc.om

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 文章分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 百科
  -
    href: /links/
    label: 友情链接

  -
    href: /about/
    label: 关于儒一

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: whooc/whooc.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
#disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: whooc
    repo: ruyi
    oauth:
        client_id: 083ec94b416ce61952f8
        client_secret: 2cfb5f73aae91e4faab9737c7d363063a1befef9
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: whooc
    repo: ruyi
    clientID: 083ec94b416ce61952f8
    clientSecret: 2cfb5f73aae91e4faab9737c7d363063a1befef9
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-80669434-1
    adsense:
        footer: true
        sidebar: true
        content_header: true
        content_footer: false
